
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--tag', 'gcr.io/animated-sign-402920/MeuProjeto', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/animated-sign-402920/MeuProjeto']
timeout: '1600s'
images:
- 'gcr.io/animated-sign-402920/MeuProjeto'
